<a href="https://colab.research.google.com/github/Simeen01/Pandas/blob/main/Pandas_Join%2C_Append.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Join can join 2 DataFrames.
Cannot join name column name, therefore, use lsuffix or rsuffix

In [ ]:
import pandas as pd

In [ ]:
df1 = pd.DataFrame({1:["A"],2:"B",3:"C"})
df2 = pd.DataFrame({4:["Bubble"],5:"Ham",6:"Bee"})

In [ ]:
display(df1,df2)

   1  2  3
0  A  B  C

        4    5    6
0  Bubble  Ham  Bee

In [ ]:
df1.join(df2) #requires different key values

   1  2  3       4    5    6
0  A  B  C  Bubble  Ham  Bee

In [ ]:
df2.join(df1)

        4    5    6  1  2  3
0  Bubble  Ham  Bee  A  B  C

In [ ]:
display(df1,df2)

   1  2  3
0  A  B  C

        4    5    6
0  Bubble  Ham  Bee

In [ ]:
#unmatched index
df1 = pd.DataFrame({1:["A"],2:"B",3:"C"}, index=["a"])
df2 = pd.DataFrame({4:["Bubble"],5:"Ham",6:"Bee"})

In [ ]:
display(df1,df2) #different indexes

   1  2  3
a  A  B  C

        4    5    6
0  Bubble  Ham  Bee

In [ ]:
df1.join(df2)

   1  2  3    4    5    6
a  A  B  C  NaN  NaN  NaN

In [ ]:
#unmatched elements
df1 = pd.DataFrame({1:["A","Apple"],2:["B","Ball"],3:["C","Cat"]})
df2 = pd.DataFrame({4:["Bubble"],5:"Ham",6:"Bee"})

In [ ]:
display(df1,df2) #2 rows in df1, 1 row in df2

       1     2    3
0      A     B    C
1  Apple  Ball  Cat

        4    5    6
0  Bubble  Ham  Bee

In [ ]:
df1.join(df2)

       1     2    3       4    5    6
0      A     B    C  Bubble  Ham  Bee
1  Apple  Ball  Cat     NaN  NaN  NaN

In [ ]:
df1 = pd.DataFrame({1:["A"],2:"B",3:"C"})
df2 = pd.DataFrame({1:["Bubble"],5:"Ham",6:"Bee"})
df3 = pd.DataFrame({1:[10],2:459,3:83})
display(df1,df2,df3)

   1  2  3
0  A  B  C

        1    5    6
0  Bubble  Ham  Bee

    1    2   3
0  10  459  83

In [ ]:
df1.join(df2,lsuffix="_a")

  1_a  2  3       1    5    6
0   A  B  C  Bubble  Ham  Bee

In [ ]:
df1.join(df2,rsuffix="_b")

   1  2  3     1_b    5    6
0  A  B  C  Bubble  Ham  Bee

Append

In [ ]:
d1 = pd.DataFrame({"ID":[1,2,3,4,5],"Class":[10,20,30,40,50]})
d2 = pd.DataFrame({"ID":[1,2,3,4,5],"Class":[11,22,33,44,55]})
display(d1,d2)

   ID  Class
0   1     10
1   2     20
2   3     30
3   4     40
4   5     50

   ID  Class
0   1     11
1   2     22
2   3     33
3   4     44
4   5     55

In [ ]:
d1.append(d2,ignore_index=True)

   ID  Class
0   1     10
1   2     20
2   3     30
3   4     40
4   5     50
5   1     11
6   2     22
7   3     33
8   4     44
9   5     55

In [ ]:
d1.append(d2,ignore_index=True,sort=True)

   Class  ID
0     10   1
1     20   2
2     30   3
3     40   4
4     50   5
5     11   1
6     22   2
7     33   3
8     44   4
9     55   5

In [ ]:
d1 = pd.DataFrame({"ID":[1,2,3],"Class":[10,20,30]})
d2 = pd.DataFrame({"ID":[1,2,3,4,5],"Class":[11,22,33,44,55]})
display(df1,df2)

       1     2    3
0      A     B    C
1  Apple  Ball  Cat

        4    5    6
0  Bubble  Ham  Bee

In [ ]:
d1.append(d2,sort=True)

   Class  ID
0     10   1
1     20   2
2     30   3
0     11   1
1     22   2
2     33   3
3     44   4
4     55   5

In [ ]:
d1.append(d2)

   ID  Class
0   1     10
1   2     20
2   3     30
0   1     11
1   2     22
2   3     33
3   4     44
4   5     55